### PR TITLE
fix the 64-bit library name.

### PR DESCRIPTION
**Pull request by andyyang**
The 64-bit libraries are libsybct64.so and libsybct_r64.so.

### CODE REVIEW

**Comment by jarib** [comment]
Thanks, I've pushed a new gem (0.0.3) with your patch. 

I'm not really maintaining this library, let me know if you (or anyone else reading this) is interested in taking it over.

**Comment by andyyang** [comment]
Hi Jari,

I'd like to maintain this library. I'm using the library in some projects.

Cheers,
Mingwei

2013/10/13 Jari Bakken notifications@github.com

**Comment by jarib** [comment]
@andyyang Great! I've added you as a collaborator on this repo. I need the email for your rubygems.org account it in order to give you push permissions there.

**Comment by andyyang** [comment]
@jarib My email address is mingwei.y at gmail dot com.

**Comment by jarib** [comment]
OK, I've added your email to the gem owners.

**Pull request merged**
